---
config:
  theme: redux
  layout: dagre
  look: neo
  themeVariables:
    edgeLabelBackground: white
---
flowchart LR
 subgraph s1["Drafting"]
    direction LR
        n1(["drafter<br>model"])
        n2["toks"]
  end
 subgraph s2["Verifying"]
    direction LR
        n3["target<br>model"]
        n4["toks"]
  end
    n1 -- "<span style=font-size:1.1em;>(<span style=font-size:1.2em;>n</span>)</span>" --> n2
    n3 -- "<span style=font-size:1.1em;>(1)</span>" --> n4
    s1 -.-> s2
    n2@{ shape: docs}
    n3@{ shape: diam}
    n4@{ shape: docs}
    style n2 fill:#FFF9C4,stroke-width:2px,stroke-dasharray: 2
    style n4 fill:#C8E6C9
    style s1 fill:transparent
    style s2 fill:transparent